### ISSUE TITLE
May I ask when you plan to make your code open-source?

### ISSUE THREAD

**Issue by WZX0Swarm0Robotics** [iit-DLSLab/DWMPC#1]
Your work is fantastic and has greatly inspired me. I would love to learn more about the details through your code. May I ask when you plan to make your code open-source? I would really appreciate it.

**Comment by lorenzo96-cmd** [comment]
Hi,
I'm happy that my work has inspired you. I'm excited to inform you that the code has been uploaded and is available as open-source in the repository.

Feel free to explore the code, and if you have any questions or feedback, don't hesitate to reach out. 
Best 
Lorenzo
